-- Tabelas
create table public.curso (
  id           bigint generated by default as identity primary key,
  curso        text not null,
  descricao    text,
  conteudo     text,
  carga_horaria text,
  categoria    text,
  nivel        text,
  ativo        boolean default true
);
create table public.user_curso (
  id       bigint generated by default as identity primary key,
  id_user  bigint not null references public.user(id) on delete cascade,
  id_curso bigint not null references public.curso(id) on delete cascade,
  status   text not null default 'pendente',
  unique(id_user, id_curso)
);
alter table public.curso enable row level security;
create policy "allow all" on public.curso for all using (true) with check (true);
alter table public.user_curso enable row level security;
create policy "allow all" on public.user_curso for all using (true) with check (true);

-- Cursos
insert into public.curso (curso, categoria, nivel, ativo) values
('Pensamento Lean',                                                              'Melhoria Contínua e Processos', 'Pleno - Senior',       true),
('PDCA',                                                                         'Melhoria Contínua e Processos', 'Assistente - Junior',  true),
('Plano de Ação com 5W2H',                                                       'Melhoria Contínua e Processos', 'Assistente - Junior',  true),
('Os 5S',                                                                        'Melhoria Contínua e Processos', 'Assistente - Junior',  true),
('Gestão de Erro',                                                               'Melhoria Contínua e Processos', 'Pleno - Senior',       true),
('Resolução de Problemas',                                                       'Melhoria Contínua e Processos', 'Pleno - Senior',       true),
('Analisar problemas e tomar decisões',                                          'Melhoria Contínua e Processos', 'Pleno - Senior',       true),
('Visão sistêmica',                                                              'Melhoria Contínua e Processos', 'Pleno - Senior',       true),
('Customer Success',                                                             'Customer Experience',           'Assistente - Junior',  true),
('Estratégias de Customer Centricity',                                           'Customer Experience',           'Pleno - Senior',       true),
('Visão do Cliente',                                                             'Customer Experience',           'Assistente - Junior',  true),
('Visão do Cliente: o atendimento que todos esperamos',                          'Customer Experience',           'Assistente - Junior',  true),
('Jornada do cliente 4.0 - use a tecnologia para encantar e fidelizar clientes', 'Customer Experience',           'Pleno - Senior',       true),
('Cultura de Atendimento',                                                       'Customer Experience',           'Assistente - Junior',  true),
('Como falar ao telefone',                                                       'Customer Experience',           'Assistente - Junior',  true),
('Tudo sobre supply chain',                                                      'Operações',                     'Pleno - Senior',       true),
('Inteligência Emocional - prevenção e transformação de conflitos',              'Comportamental',                'Pleno - Senior',       true),
('Inteligência emocional',                                                       'Comportamental',                'Assistente - Junior',  true),
('Seja você! Aceite suas vulnerabilidades!',                                     'Comportamental',                'Assistente - Junior',  true),
('Gestão de Conflitos',                                                          'Comportamental',                'Pleno - Senior',       true),
('Feedback',                                                                     'Comportamental',                'Assistente - Junior',  true),
('Foco no Resultado',                                                            'Comportamental',                'Assistente - Junior',  true),
('Desenvolver disciplina para alcançar metas',                                   'Comportamental',                'Pleno - Senior',       true),
('Colaboração Criativa',                                                         'Comportamental',                'Pleno - Senior',       true),
('Alto Desempenho',                                                              'Comportamental',                'Pleno - Senior',       true),
('Trabalho Remoto - Como se manter produtivo e gerir o tempo',                   'Produtividade',                 'Assistente - Junior',  true),
('Organização digital',                                                          'Produtividade',                 'Assistente - Junior',  true),
('Planejamento para fazer acontecer - Ferramentas',                              'Produtividade',                 'Assistente - Junior',  true),
('Excel Básico',                                                                 'Tecnologia e Ferramentas',      'Assistente - Junior',  true),
('Excel Intermediário',                                                          'Tecnologia e Ferramentas',      'Assistente - Junior',  true),
('Excel Avançado',                                                               'Tecnologia e Ferramentas',      'Pleno - Senior',       true),
('Power BI introdutório',                                                        'Tecnologia e Ferramentas',      'Pleno - Senior',       true),
('Power BI (Office 365)',                                                        'Tecnologia e Ferramentas',      'Pleno - Senior',       true),
('E-mail e redes sociais',                                                       'Tecnologia e Ferramentas',      'Assistente - Junior',  true),
('Engenharia de prompt - Como criar instruções claras e eficazes para a IA',     'Inteligência Artificial',       'Assistente - Junior',  true),
('Domine o poder do ChatGPT',                                                    'Inteligência Artificial',       'Assistente - Junior',  true),
('Descubra o potencial da IA no seu dia a dia',                                  'Inteligência Artificial',       'Assistente - Junior',  true),
('Como usar a IA com segurança e responsabilidade',                              'Inteligência Artificial',       'Assistente - Junior',  true),
('Inteligência Artificial',                                                      'Inteligência Artificial',       'Pleno - Senior',       true),
('Planejamento Estratégico',                                                     'Gestão e Liderança',            'Pleno - Senior',       true),
('PITCH - Apresentações rápidas e de impacto',                                   'Gestão e Liderança',            'Pleno - Senior',       true),
('Gerenciamento ágil de projetos - primeiros passos no Scrum Kanban e Lean',     'Gestão e Liderança',            'Pleno - Senior',       true),
('Liderança de equipes e projetos',                                              'Gestão e Liderança',            'Pleno - Senior',       true),
('Construir um marketing pessoal',                                               'Gestão e Liderança',            'Assistente - Junior',  true),
('Segurança da Informação',                                                      'Compliance',                    'Assistente - Junior',  true),
('Código de Ética e Conduta',                                                    'Compliance',                    'Assistente - Junior',  true);
