-- Execute isso no SQL Editor do seu projeto Supabase
-- https://supabase.com/dashboard/project/kztzrejrhpsefvpugynq/sql

create table public.organograma (
  id         bigint generated by default as identity not null,
  id_user    bigint not null references public.user(id) on delete cascade,
  id_manager bigint null     references public.user(id) on delete set null,
  constraint organograma_pkey primary key (id),
  constraint organograma_unique unique (id_user) -- cada pessoa tem só 1 gestor direto
);

-- Habilita RLS (recomendado)
alter table public.organograma enable row level security;

-- Política permissiva para desenvolvimento (ajuste conforme sua autenticação)
create policy "allow all" on public.organograma for all using (true) with check (true);

-- Mesma coisa na tabela user se ainda não tiver
alter table public.user enable row level security;
create policy "allow all" on public.user for all using (true) with check (true);
