-- Tabela de atribuições (ex: "Suporte", "Comercial", "TI")
create table public.atribuicao (
  id    bigint generated by default as identity not null,
  nome  text not null,
  cor   text not null default '#6366f1',
  constraint atribuicao_pkey primary key (id)
);

-- Relação N:N entre user e atribuição
create table public.user_atribuicao (
  id            bigint generated by default as identity not null,
  id_user       bigint not null references public.user(id) on delete cascade,
  id_atribuicao bigint not null references public.atribuicao(id) on delete cascade,
  constraint user_atribuicao_pkey primary key (id),
  constraint user_atribuicao_unique unique (id_user, id_atribuicao)
);

alter table public.atribuicao enable row level security;
create policy "allow all" on public.atribuicao for all using (true) with check (true);

alter table public.user_atribuicao enable row level security;
create policy "allow all" on public.user_atribuicao for all using (true) with check (true);
